service: authorization-service
useDotenv: true
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  environment:
    ADMIN_PASSWORD: ${env:admin}

functions:
  basicAuthorizer:
    handler: ./handlers/basicAuthorizer.invoke
    events:
      - http:
          path: /token
          method: get
          cors: true
          authorizer:
            name: tokenAuthorizer
            type: token
            arn: "arn:aws:lambda:eu-west-1:592443183309:function:authorization-service-dev-basicAuthorizer"
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
            